package android.provider;

import java.StdTypes;
extern interface ContactsContract_DataColumnsWithJoins  implements android.provider.BaseColumns, android.provider.ContactsContract_DataColumns, android.provider.ContactsContract_StatusColumns, android.provider.ContactsContract_RawContactsColumns, android.provider.ContactsContract_ContactsColumns, android.provider.ContactsContract_ContactOptionsColumns, android.provider.ContactsContract_ContactStatusColumns
{


}