package android.provider;

import java.StdTypes;
extern interface ContactsContract_DataColumnsWithJoins  implements android.provider.BaseColumns, implements android.provider.ContactsContract_DataColumns, implements android.provider.ContactsContract_StatusColumns, implements android.provider.ContactsContract_RawContactsColumns, implements android.provider.ContactsContract_ContactsColumns, implements android.provider.ContactsContract_ContactOptionsColumns, implements android.provider.ContactsContract_ContactStatusColumns
{


}
